version = 3.9.6
runner.dialect=scala212
style = defaultWithAlign
maxColumn = 120
project.excludePaths = ["glob:**FolderCompactionUtilsSpec.scala"]
project.git = true
align.tokens."+" = [
  {code = "=>", owner = "Case"},
  {code = "%", owner = "Term.ApplyInfix"},
  {code = "%%", owner = "Term.ApplyInfix"}
]
align.arrowEnumeratorGenerator = true
rewrite.rules = [
  SortImports,
  SortModifiers
]
