/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ActionDTO(
  /* The action id. */
  id: Option[Int] = None,
  /* The identity of the user that performed the action. */
  userIdentity: Option[String] = None,
  /* The timestamp of the action. */
  timestamp: Option[String] = None,
  /* The id of the source component. */
  sourceId: Option[String] = None,
  /* The name of the source component. */
  sourceName: Option[String] = None,
  /* The type of the source component. */
  sourceType: Option[String] = None,
  componentDetails: Option[Any] = None,
  /* The operation that was performed. */
  operation: Option[String] = None,
  actionDetails: Option[Any] = None
) extends ApiModel


