/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ConnectableComponent(
  /* The id of the connectable component. */
  id: String,
  /* The type of component the connectable is. */
  `type`: ConnectableComponentEnums.`Type`,
  /* The id of the group that the connectable component resides in */
  groupId: String,
  /* The name of the connectable component */
  name: Option[String] = None,
  /* The comments for the connectable component. */
  comments: Option[String] = None
) extends ApiModel

object ConnectableComponentEnums {

  type `Type` = `Type`.Value
  object `Type` extends Enumeration {
    val PROCESSOR = Value("PROCESSOR")
    val REMOTEINPUTPORT = Value("REMOTE_INPUT_PORT")
    val REMOTEOUTPUTPORT = Value("REMOTE_OUTPUT_PORT")
    val INPUTPORT = Value("INPUT_PORT")
    val OUTPUTPORT = Value("OUTPUT_PORT")
    val FUNNEL = Value("FUNNEL")
  }

}

