/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ConnectionStatusPredictionsSnapshotDTO(
  /* The predicted number of milliseconds before the connection will have backpressure applied, based on the queued count. */
  predictedMillisUntilCountBackpressure: Option[Long] = None,
  /* The predicted number of milliseconds before the connection will have backpressure applied, based on the total number of bytes in the queue. */
  predictedMillisUntilBytesBackpressure: Option[Long] = None,
  /* The configured interval (in seconds) for predicting connection queue count and size (and percent usage). */
  predictionIntervalSeconds: Option[Int] = None,
  /* The predicted number of queued objects at the next configured interval. */
  predictedCountAtNextInterval: Option[Int] = None,
  /* The predicted total number of bytes in the queue at the next configured interval. */
  predictedBytesAtNextInterval: Option[Long] = None,
  /* Predicted connection percent use regarding queued flow files count and backpressure threshold if configured. */
  predictedPercentCount: Option[Int] = None,
  /* Predicted connection percent use regarding queued flow files size and backpressure threshold if configured. */
  predictedPercentBytes: Option[Int] = None
) extends ApiModel


