/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class DropRequestDTO(
  /* The id for this drop request. */
  id: Option[String] = None,
  /* The URI for future requests to this drop request. */
  uri: Option[String] = None,
  /* The timestamp when the query was submitted. */
  submissionTime: Option[String] = None,
  /* The last time this drop request was updated. */
  lastUpdated: Option[String] = None,
  /* The current percent complete. */
  percentCompleted: Option[Int] = None,
  /* Whether the query has finished. */
  finished: Option[Boolean] = None,
  /* The reason, if any, that this drop request failed. */
  failureReason: Option[String] = None,
  /* The number of flow files currently queued. */
  currentCount: Option[Int] = None,
  /* The size of flow files currently queued in bytes. */
  currentSize: Option[Long] = None,
  /* The count and size of flow files currently queued. */
  current: Option[String] = None,
  /* The number of flow files to be dropped as a result of this request. */
  originalCount: Option[Int] = None,
  /* The size of flow files to be dropped as a result of this request in bytes. */
  originalSize: Option[Long] = None,
  /* The count and size of flow files to be dropped as a result of this request. */
  original: Option[String] = None,
  /* The number of flow files that have been dropped thus far. */
  droppedCount: Option[Int] = None,
  /* The size of flow files that have been dropped thus far in bytes. */
  droppedSize: Option[Long] = None,
  /* The count and size of flow files that have been dropped thus far. */
  dropped: Option[String] = None,
  /* The current state of the drop request. */
  state: Option[String] = None
) extends ApiModel


