/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class FlowConfigurationDTO(
  /* Whether this NiFi supports a managed authorizer. Managed authorizers can visualize users, groups, and policies in the UI. */
  supportsManagedAuthorizer: Option[Boolean] = None,
  /* Whether this NiFi supports a configurable authorizer. */
  supportsConfigurableAuthorizer: Option[Boolean] = None,
  /* Whether this NiFi supports configurable users and groups. */
  supportsConfigurableUsersAndGroups: Option[Boolean] = None,
  /* The interval in seconds between the automatic NiFi refresh requests. */
  autoRefreshIntervalSeconds: Option[Long] = None,
  /* The current time on the system. */
  currentTime: Option[String] = None,
  /* The time offset of the system. */
  timeOffset: Option[Int] = None,
  /* The default back pressure object threshold. */
  defaultBackPressureObjectThreshold: Option[Long] = None,
  /* The default back pressure data size threshold. */
  defaultBackPressureDataSizeThreshold: Option[String] = None
) extends ApiModel


