/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class FlowDTO(
  /* The process groups in this flow. */
  processGroups: Option[Set[ProcessGroupEntity]] = None,
  /* The remote process groups in this flow. */
  remoteProcessGroups: Option[Set[RemoteProcessGroupEntity]] = None,
  /* The processors in this flow. */
  processors: Option[Set[ProcessorEntity]] = None,
  /* The input ports in this flow. */
  inputPorts: Option[Set[PortEntity]] = None,
  /* The output ports in this flow. */
  outputPorts: Option[Set[PortEntity]] = None,
  /* The connections in this flow. */
  connections: Option[Set[ConnectionEntity]] = None,
  /* The labels in this flow. */
  labels: Option[Set[LabelEntity]] = None,
  /* The funnels in this flow. */
  funnels: Option[Set[FunnelEntity]] = None
) extends ApiModel


