/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class FlowSnippetDTO(
  /* The process groups in this flow snippet. */
  processGroups: Option[Set[ProcessGroupDTO]] = None,
  /* The remote process groups in this flow snippet. */
  remoteProcessGroups: Option[Set[RemoteProcessGroupDTO]] = None,
  /* The processors in this flow snippet. */
  processors: Option[Set[ProcessorDTO]] = None,
  /* The input ports in this flow snippet. */
  inputPorts: Option[Set[PortDTO]] = None,
  /* The output ports in this flow snippet. */
  outputPorts: Option[Set[PortDTO]] = None,
  /* The connections in this flow snippet. */
  connections: Option[Set[ConnectionDTO]] = None,
  /* The labels in this flow snippet. */
  labels: Option[Set[LabelDTO]] = None,
  /* The funnels in this flow snippet. */
  funnels: Option[Set[FunnelDTO]] = None,
  /* The controller services in this flow snippet. */
  controllerServices: Option[Set[ControllerServiceDTO]] = None
) extends ApiModel


