/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class FlowBreadcrumbEntity(
  /* The id of this ancestor ProcessGroup. */
  id: Option[String] = None,
  permissions: Option[PermissionsDTO] = None,
  /* The current state of the Process Group, as it relates to the Versioned Flow */
  versionedFlowState: Option[FlowBreadcrumbEntityEnums.VersionedFlowState] = None,
  breadcrumb: Option[FlowBreadcrumbDTO] = None,
  parentBreadcrumb: Option[FlowBreadcrumbEntity] = None
) extends ApiModel

object FlowBreadcrumbEntityEnums {

  type VersionedFlowState = VersionedFlowState.Value
  object VersionedFlowState extends Enumeration {
    val LOCALLYMODIFIED = Value("LOCALLY_MODIFIED")
    val STALE = Value("STALE")
    val LOCALLYMODIFIEDANDSTALE = Value("LOCALLY_MODIFIED_AND_STALE")
    val UPTODATE = Value("UP_TO_DATE")
    val SYNCFAILURE = Value("SYNC_FAILURE")
  }

}

