/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class LineageDTO(
  /* The id of this lineage query. */
  id: Option[String] = None,
  /* The URI for this lineage query for later retrieval and deletion. */
  uri: Option[String] = None,
  /* When the lineage query was submitted. */
  submissionTime: Option[String] = None,
  /* When the lineage query will expire. */
  expiration: Option[String] = None,
  /* The percent complete for the lineage query. */
  percentCompleted: Option[Int] = None,
  /* Whether the lineage query has finished. */
  finished: Option[Boolean] = None,
  request: Option[LineageRequestDTO] = None,
  results: Option[LineageResultsDTO] = None
) extends ApiModel


