/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class NodeDTO(
  /* The id of the node. */
  nodeId: Option[String] = None,
  /* The node's host/ip address. */
  address: Option[String] = None,
  /* The port the node is listening for API requests. */
  apiPort: Option[Int] = None,
  /* The node's status. */
  status: Option[String] = None,
  /* the time of the nodes's last heartbeat. */
  heartbeat: Option[String] = None,
  /* The time of the node's last connection request. */
  connectionRequested: Option[String] = None,
  /* The roles of this node. */
  roles: Option[Set[String]] = None,
  /* The active threads for the NiFi on the node. */
  activeThreadCount: Option[Int] = None,
  /* The queue the NiFi on the node. */
  queued: Option[String] = None,
  /* The node's events. */
  events: Option[Seq[NodeEventDTO]] = None,
  /* The time at which this Node was last refreshed. */
  nodeStartTime: Option[String] = None
) extends ApiModel


