/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class NodeStatusSnapshotsDTO(
  /* The id of the node. */
  nodeId: Option[String] = None,
  /* The node's host/ip address. */
  address: Option[String] = None,
  /* The port the node is listening for API requests. */
  apiPort: Option[Int] = None,
  /* A list of StatusSnapshotDTO objects that provide the actual metric values for the component for this node. */
  statusSnapshots: Option[Seq[StatusSnapshotDTO]] = None
) extends ApiModel


