/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ProcessGroupStatusDTO(
  /* The ID of the Process Group */
  id: Option[String] = None,
  /* The name of the Process Group */
  name: Option[String] = None,
  /* The time the status for the process group was last refreshed. */
  statsLastRefreshed: Option[String] = None,
  aggregateSnapshot: Option[ProcessGroupStatusSnapshotDTO] = None,
  /* The status reported by each node in the cluster. If the NiFi instance is a standalone instance, rather than a clustered instance, this value may be null. */
  nodeSnapshots: Option[Seq[NodeProcessGroupStatusSnapshotDTO]] = None
) extends ApiModel


