/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ProcessGroupFlowDTO(
  /* The id of the component. */
  id: Option[String] = None,
  /* The URI for futures requests to the component. */
  uri: Option[String] = None,
  /* The id of parent process group of this component if applicable. */
  parentGroupId: Option[String] = None,
  parameterContext: Option[ParameterContextReferenceEntity] = None,
  breadcrumb: Option[FlowBreadcrumbEntity] = None,
  flow: Option[FlowDTO] = None,
  /* The time the flow for the process group was last refreshed. */
  lastRefreshed: Option[String] = None
) extends ApiModel


