/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class PropertyDescriptorDTO(
  /* The name for the property. */
  name: Option[String] = None,
  /* The human readable name for the property. */
  displayName: Option[String] = None,
  /* The description for the property. Used to relay additional details to a user or provide a mechanism of documenting intent. */
  description: Option[String] = None,
  /* The default value for the property. */
  defaultValue: Option[String] = None,
  /* Allowable values for the property. If empty then the allowed values are not constrained. */
  allowableValues: Option[Seq[AllowableValueEntity]] = None,
  /* Whether the property is required. */
  required: Option[Boolean] = None,
  /* Whether the property is sensitive and protected whenever stored or represented. */
  sensitive: Option[Boolean] = None,
  /* Whether the property is dynamic (user-defined). */
  dynamic: Option[Boolean] = None,
  /* Whether the property supports expression language. */
  supportsEl: Option[Boolean] = None,
  /* Scope of the Expression Language evaluation for the property. */
  expressionLanguageScope: Option[String] = None,
  /* If the property identifies a controller service this returns the fully qualified type. */
  identifiesControllerService: Option[String] = None,
  identifiesControllerServiceBundle: Option[BundleDTO] = None
) extends ApiModel


