/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ProvenanceDTO(
  /* The id of the provenance query. */
  id: Option[String] = None,
  /* The URI for this query. Used for obtaining/deleting the request at a later time */
  uri: Option[String] = None,
  /* The timestamp when the query was submitted. */
  submissionTime: Option[String] = None,
  /* The timestamp when the query will expire. */
  expiration: Option[String] = None,
  /* The current percent complete. */
  percentCompleted: Option[Int] = None,
  /* Whether the query has finished. */
  finished: Option[Boolean] = None,
  request: Option[ProvenanceRequestDTO] = None,
  results: Option[ProvenanceResultsDTO] = None
) extends ApiModel


