/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ProvenanceRequestDTO(
  /* The search terms used to perform the search. */
  searchTerms: Option[Map[String, String]] = None,
  /* The id of the node in the cluster where this provenance originated. */
  clusterNodeId: Option[String] = None,
  /* The earliest event time to include in the query. */
  startDate: Option[String] = None,
  /* The latest event time to include in the query. */
  endDate: Option[String] = None,
  /* The minimum file size to include in the query. */
  minimumFileSize: Option[String] = None,
  /* The maximum file size to include in the query. */
  maximumFileSize: Option[String] = None,
  /* The maximum number of results to include. */
  maxResults: Option[Int] = None,
  /* Whether or not to summarize provenance events returned. This property is false by default. */
  summarize: Option[Boolean] = None,
  /* Whether or not incremental results are returned. If false, provenance events are only returned once the query completes. This property is true by default. */
  incrementalResults: Option[Boolean] = None
) extends ApiModel


