/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class ProvenanceResultsDTO(
  /* The provenance events that matched the search criteria. */
  provenanceEvents: Option[Seq[ProvenanceEventDTO]] = None,
  /* The total number of results formatted. */
  total: Option[String] = None,
  /* The total number of results. */
  totalCount: Option[Long] = None,
  /* Then the search was performed. */
  generated: Option[String] = None,
  /* The oldest event available in the provenance repository. */
  oldestEvent: Option[String] = None,
  /* The time offset of the server that's used for event time. */
  timeOffset: Option[Int] = None,
  /* Any errors that occurred while performing the provenance request. */
  errors: Option[Set[String]] = None
) extends ApiModel


