/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class RemoteProcessGroupPortDTO(
  /* The id of the port. */
  id: Option[String] = None,
  /* The id of the target port. */
  targetId: Option[String] = None,
  /* The ID of the corresponding component that is under version control */
  versionedComponentId: Option[String] = None,
  /* The id of the remote process group that the port resides in. */
  groupId: Option[String] = None,
  /* The name of the target port. */
  name: Option[String] = None,
  /* The comments as configured on the target port. */
  comments: Option[String] = None,
  /* The number of task that may transmit flowfiles to the target port concurrently. */
  concurrentlySchedulableTaskCount: Option[Int] = None,
  /* Whether the remote port is configured for transmission. */
  transmitting: Option[Boolean] = None,
  /* Whether the flowfiles are compressed when sent to the target port. */
  useCompression: Option[Boolean] = None,
  /* Whether the target port exists. */
  exists: Option[Boolean] = None,
  /* Whether the target port is running. */
  targetRunning: Option[Boolean] = None,
  /* Whether the port has either an incoming or outgoing connection. */
  connected: Option[Boolean] = None,
  batchSettings: Option[BatchSettingsDTO] = None
) extends ApiModel


