/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class SearchResultsDTO(
  /* The processors that matched the search. */
  processorResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The connections that matched the search. */
  connectionResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The process groups that matched the search. */
  processGroupResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The input ports that matched the search. */
  inputPortResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The output ports that matched the search. */
  outputPortResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The remote process groups that matched the search. */
  remoteProcessGroupResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The funnels that matched the search. */
  funnelResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The parameter contexts that matched the search. */
  parameterContextResults: Option[Seq[ComponentSearchResultDTO]] = None,
  /* The parameters that matched the search. */
  parameterResults: Option[Seq[ComponentSearchResultDTO]] = None
) extends ApiModel


