/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class StatusHistoryDTO(
  /* When the status history was generated. */
  generated: Option[String] = None,
  /* A Map of key/value pairs that describe the component that the status history belongs to */
  componentDetails: Option[Map[String, String]] = None,
  /* The Descriptors that provide information on each of the metrics provided in the status history */
  fieldDescriptors: Option[Seq[StatusDescriptorDTO]] = None,
  /* A list of StatusSnapshotDTO objects that provide the actual metric values for the component. If the NiFi instance is clustered, this will represent the aggregate status across all nodes. If the NiFi instance is not clustered, this will represent the status of the entire NiFi instance. */
  aggregateSnapshots: Option[Seq[StatusSnapshotDTO]] = None,
  /* The NodeStatusSnapshotsDTO objects that provide the actual metric values for the component, for each node. If the NiFi instance is not clustered, this value will be null. */
  nodeSnapshots: Option[Seq[NodeStatusSnapshotsDTO]] = None
) extends ApiModel


