/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class StorageUsageDTO(
  /* The identifier of this storage location. The identifier will correspond to the identifier keyed in the storage configuration. */
  identifier: Option[String] = None,
  /* Amount of free space. */
  freeSpace: Option[String] = None,
  /* Amount of total space. */
  totalSpace: Option[String] = None,
  /* Amount of used space. */
  usedSpace: Option[String] = None,
  /* The number of bytes of free space. */
  freeSpaceBytes: Option[Long] = None,
  /* The number of bytes of total space. */
  totalSpaceBytes: Option[Long] = None,
  /* The number of bytes of used space. */
  usedSpaceBytes: Option[Long] = None,
  /* Utilization of this storage location. */
  utilization: Option[String] = None
) extends ApiModel


