/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class VariableDTO(
  /* The name of the variable */
  name: Option[String] = None,
  /* The value of the variable */
  value: Option[String] = None,
  /* The ID of the Process Group where this Variable is defined */
  processGroupId: Option[String] = None,
  /* A set of all components that will be affected if the value of this variable is changed */
  affectedComponents: Option[Set[AffectedComponentEntity]] = None
) extends ApiModel


