/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class VersionedFlowDTO(
  /* The ID of the registry that the flow is tracked to */
  registryId: Option[String] = None,
  /* The ID of the bucket where the flow is stored */
  bucketId: Option[String] = None,
  /* The ID of the flow */
  flowId: Option[String] = None,
  /* The name of the flow */
  flowName: Option[String] = None,
  /* A description of the flow */
  description: Option[String] = None,
  /* Comments for the changeset */
  comments: Option[String] = None,
  /* The action being performed */
  action: Option[VersionedFlowDTOEnums.Action] = None
) extends ApiModel

object VersionedFlowDTOEnums {

  type Action = Action.Value
  object Action extends Enumeration {
    val COMMIT = Value("COMMIT")
    val FORCECOMMIT = Value("FORCE_COMMIT")
  }

}

