/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class VersionedProcessGroup(
  /* The component's unique identifier */
  identifier: Option[String] = None,
  /* The component's name */
  name: Option[String] = None,
  /* The user-supplied comments for the component */
  comments: Option[String] = None,
  position: Option[Position] = None,
  /* The child Process Groups */
  processGroups: Option[Set[VersionedProcessGroup]] = None,
  /* The Remote Process Groups */
  remoteProcessGroups: Option[Set[VersionedRemoteProcessGroup]] = None,
  /* The Processors */
  processors: Option[Set[VersionedProcessor]] = None,
  /* The Input Ports */
  inputPorts: Option[Set[VersionedPort]] = None,
  /* The Output Ports */
  outputPorts: Option[Set[VersionedPort]] = None,
  /* The Connections */
  connections: Option[Set[VersionedConnection]] = None,
  /* The Labels */
  labels: Option[Set[VersionedLabel]] = None,
  /* The Funnels */
  funnels: Option[Set[VersionedFunnel]] = None,
  /* The Controller Services */
  controllerServices: Option[Set[VersionedControllerService]] = None,
  versionedFlowCoordinates: Option[VersionedFlowCoordinates] = None,
  /* The Variables in the Variable Registry for this Process Group (not including any ancestor or descendant Process Groups) */
  variables: Option[Map[String, String]] = None,
  /* The name of the parameter context used by this process group */
  parameterContextName: Option[String] = None,
  componentType: Option[VersionedProcessGroupEnums.ComponentType] = None,
  /* The ID of the Process Group that this component belongs to */
  groupIdentifier: Option[String] = None
) extends ApiModel

object VersionedProcessGroupEnums {

  type ComponentType = ComponentType.Value
  object ComponentType extends Enumeration {
    val CONNECTION = Value("CONNECTION")
    val PROCESSOR = Value("PROCESSOR")
    val PROCESSGROUP = Value("PROCESS_GROUP")
    val REMOTEPROCESSGROUP = Value("REMOTE_PROCESS_GROUP")
    val INPUTPORT = Value("INPUT_PORT")
    val OUTPUTPORT = Value("OUTPUT_PORT")
    val REMOTEINPUTPORT = Value("REMOTE_INPUT_PORT")
    val REMOTEOUTPUTPORT = Value("REMOTE_OUTPUT_PORT")
    val FUNNEL = Value("FUNNEL")
    val LABEL = Value("LABEL")
    val CONTROLLERSERVICE = Value("CONTROLLER_SERVICE")
  }

}

