/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class VersionedFlowSnapshotMetadata(
  link: Option[JaxbLink] = None,
  /* The identifier of the bucket this snapshot belongs to. */
  bucketIdentifier: String,
  /* The identifier of the flow this snapshot belongs to. */
  flowIdentifier: String,
  /* The version of this snapshot of the flow. */
  version: Int,
  /* The timestamp when the flow was saved, as milliseconds since epoch. */
  timestamp: Option[Long] = None,
  /* The user that created this snapshot of the flow. */
  author: Option[String] = None,
  /* The comments provided by the user when creating the snapshot. */
  comments: Option[String] = None
) extends ApiModel


