/**
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.11.4
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.agilelab.bigdata.nifi.client.model

import it.agilelab.bigdata.nifi.client.core.ApiModel

case class VersionedFlowUpdateRequestDTO(
  /* The unique ID of this request. */
  requestId: Option[String] = None,
  /* The unique ID of the Process Group that the variable registry belongs to */
  processGroupId: Option[String] = None,
  /* The URI for future requests to this drop request. */
  uri: Option[String] = None,
  /* The last time this request was updated. */
  lastUpdated: Option[String] = None,
  /* Whether or not this request has completed */
  complete: Option[Boolean] = None,
  /* An explanation of why this request failed, or null if this request has not failed */
  failureReason: Option[String] = None,
  /* The percentage complete for the request, between 0 and 100 */
  percentCompleted: Option[Int] = None,
  /* The state of the request */
  state: Option[String] = None,
  versionControlInformation: Option[VersionControlInformationDTO] = None
) extends ApiModel


