version: '2'
services:

  solr:
    build: ./solr/
    image: solr_cdh:5.12
    container_name: solr
    hostname: solr
    environment:
      SOLR_ZK_ENSEMBLE: zookeeper:2181/solr
      dataDir: /data
      CATALINA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "8983:8983"
    volumes:
      - "./data/solr:/data"
    mem_limit: 500m
    links:
      - zookeeper
    depends_on:
      - zookeeper

  banana:
    image: pschatzmann/banana
    container_name: banana
    hostname: banana
    ports:
      - "32770:80"
    volumes:
      - ./banana/dashboards/:/usr/share/nginx/html/app/dashboards
    links:
      - solr
    depends_on:
      - solr

networks:
  default:
    external:
      name: wasp-docker
