package it.agilelab.bigdata.wasp.core.models.configuration

import it.agilelab.bigdata.wasp.core.utils.ConnectionConfig

abstract class SparkConfigModel(val appName: String,
                                val master: ConnectionConfig,
                                val driverCores: Int,
                                val driverMemory: String,
                                val driverHostname: String,
                                val driverPort: Int,
                                val executorCores: Int,
                                val executorMemory: String,
                                val executorInstances: Int,
                                val additionalJars: Option[Seq[String]],
                                val yarnJar: String,
                                val blockManagerPort: Int,
                                val broadcastPort: Int,
                                val fileserverPort: Int,
                                val name: String)

case class SparkStreamingConfigModel(override val appName: String,
                                     override val master: ConnectionConfig,
                                     override val driverCores: Int,
                                     override val driverMemory: String,
                                     override val driverHostname: String,
                                     override val driverPort: Int,
                                     override val executorCores: Int,
                                     override val executorMemory: String,
                                     override val executorInstances: Int,
                                     override val additionalJars: Option[Seq[String]],
                                     override val yarnJar: String,
                                     override val blockManagerPort: Int,
                                     override val broadcastPort: Int,
                                     override val fileserverPort: Int,
                                     streamingBatchIntervalMs: Int,
                                     checkpointDir: String,
                                     override val name: String)
  extends SparkConfigModel(appName,
                           master,
                           driverCores,
                           driverMemory,
                           driverHostname,
                           driverPort,
                           executorCores,
                           executorMemory,
                           executorInstances,
                           additionalJars,
                           yarnJar,
                           blockManagerPort,
                           broadcastPort,
                           fileserverPort,
                           name)

case class SparkBatchConfigModel(override val appName: String,
                                 override val master: ConnectionConfig,
                                 override val driverCores: Int,
                                 override val driverMemory: String,
                                 override val driverHostname: String,
                                 override val driverPort: Int,
                                 override val executorCores: Int,
                                 override val executorMemory: String,
                                 override val executorInstances: Int,
                                 override val additionalJars: Option[Seq[String]],
                                 override val yarnJar: String,
                                 override val blockManagerPort: Int,
                                 override val broadcastPort: Int,
                                 override val fileserverPort: Int,
                                 override val name: String)
  extends SparkConfigModel(appName,
                           master,
                           driverCores,
                           driverMemory,
                           driverHostname,
                           driverPort,
                           executorCores,
                           executorMemory,
                           executorInstances,
                           additionalJars,
                           yarnJar,
                           blockManagerPort,
                           broadcastPort,
                           fileserverPort,
                           name)