version: '2'
services:
  mongo:
    image: mongo:3.0.2
    container_name: mongo
    ports:
     - "27017:27017"
    volumes:
     - "./data/mongo:/data/db"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2182:2181"
    volumes:
      - "./zookeeper:/opt/zookeeper-3.4.6/conf"
      - "./data/zookeeper:/opt/zookeeper-3.4.6/data"

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka # the standard ip of docker0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1001
    ports:
      - "9092:9092"
    volumes:
      - "./data/kafka:/kafka/"
    depends_on:
      - zookeeper

  spark-master:
    # Change to the spark version when gettyimages will put the image tag
    image: gettyimages/spark:2.2.0-hadoop-2.7
    command: ["bin/spark-class","org.apache.spark.deploy.master.Master","-h","spark-master"]
    container_name: spark-master
    environment:
      SPARK_CONF_DIR: /etc/spark
    expose:
      - "7001"
      - "7002"
      - "7003"
      - "7004"
      - "7005"
      - "7006"
    ports:
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
      - "18080:18080"
    volumes:
      - "./spark-master:/etc/spark"
      - "./data/spark-master:/tmp/data"

  spark-worker:
    image: gettyimages/spark:2.2.0-hadoop-2.7
    command: ["bin/spark-class","org.apache.spark.deploy.worker.Worker","spark://spark-master:7077"]
    container_name: spark-worker
    environment:
      SPARK_CONF_DIR: /etc/spark
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
    expose:
      - "7012"
      - "7013"
      - "7014"
      - "7015"
      - "7016"
      - "8881"
    ports:
      - "8081:8081"
    volumes:
      - "./spark-worker:/etc/spark"
      - "./data/spark-worker:/tmp/data"
    depends_on:
      - spark-master
  elastickibana:
    image: devdb/kibana:latest
    container_name: elastickibana
    ports:
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./elasticsearch:/opt/elasticsearch/config"
      - "./kibana:/opt/kibana/config"
      - "./data/elastickibana:/opt/elasticsearch/data/elasticsearch"
networks:
  default:
    external:
      name: wasp-docker
