wasp {
  akka {
    cluster {
      roles = ["producers", "logger"]
    }
    remote {
      artery {
        enabled = on
        canonical.port = 0
        canonical.hostname = "localhost"
      }
    }
  }
}