wasp {
  akka {
    cluster {
      roles = ["producers", "logger"]
    }
    remote {
      artery.enabled = false
      classic {
        netty.tcp {
          port = 0
          hostname = "localhost"
        }
      }
    }
  }
}