package it.agilelab.bigdata.wasp.core.eventengine

object EventEngineConstants {

  val	EVENT_STRATEGY:	String	=	"eventStrategy"
  val TRIGGER_INTERVAL_MS: String = "trigger-interval-ms"
  val	CONTENT_TYPE:	String	=	"contentType"
  val	DATASTORE_MODEL_NAME:	String	=	"datastoreModelName"
  val	ENABLE_AGGREGATION:	String	=	"enableAggregation"
  val	EVENT_ID:	String	=	"eventId"
  val	EVENT_RULE_NAME:	String	=	"eventRuleName"
  val	EVENT_RULES:	String	=	"eventRules"
  val	EVENT_TYPE:	String	=	"eventType"
  val	KEY:	String	=	"key"
  val	LINE_SEPARATOR:	String	=	"\n\n--------------------------------------------------------------------------------\n\n"
  val	MAIL_BCC:	String	=	"mailBcc"
  val	MAIL_CC:	String	=	"mailCc"
  val	MAIL_CONTENT:	String	=	"mailContent"
  val	MAIL_RULES:	String	=	"mailRules"
  val	MAIL_SUBJECT:	String	=	"mailSubject"
  val	MAIL_TO:	String	=	"mailTo"
  val	MAILING_RULE_NAME:	String	=	"mailingRuleName"
  val	MAILING_STRATEGY:	String	=	"mailingStrategy"
  val	MATCHES_FLAG:	String	=	"matches"
  val	MODEL_NAME:	String	=	"modelName"
  val	MODEL_TYPE:	String	=	"modelType"
  val	NAME:	String	=	"name"
  val	OPTIONS:	String	=	"options"
  val	PAYLOAD:	String	=	"payload"
  val	RANDOM_STRING_LENGTH:	Int	=	16
  val IS_SYSTEM: String = "isSystem"
  val	READER:	String	=	"reader"
  val	RECIPIENT:	String	=	"recipient"
  val	SEVERITY_EXPRESSION:	String	=	"severityExpression"
  val	SEVERITY:	String	=	"severity"
  val	SOURCE_ID_EXPRESSION:	String	=	"sourceIdExpression"
  val	SOURCE_ID:	String	=	"sourceId"
  val	SOURCE:	String	=	"source"
  val	STATEMENT:	String	=	"statement"
  val	STREAMING_SOURCE:	String	=	"streamingSource"
  val	SUBJECT_EXPR:	String	=	"subjectExpression"
  val	TEMPLATE_KEY:	String	=	"templatePath"
  val	TEMPLATE_PATH:	String	=	"templatePath"
  val	TIMESTAMP:	String	=	"timestamp"
  val	TRIGGER:	String	=	"trigger"
  val	TYPE_EXPRESSION:	String	=	"typeExpression"
  val	VALUE:	String	=	"value"
  val	WRITER:	String	=	"writer"

}
